---
title: "Planificación"
sidebar: false
toc: false
page-layout: full
---

Los dos componentes centrales del curso son las clases teóricas y las actividades prácticas. Las **clases** se realizarán los días **Lunes de 12:10 a 13:50** y de **14:55 a 16:35**.


- [**Clases**]() (<i class="fas fa-chalkboard-teacher"></i> ): Lecturas y documentos de presentación

- [**Prácticas y evaluaciones**]() (<i class="fas fa-user-edit"></i>): Actividades prácticas a desarrollar durante la semana.

- [**Lecturas**]() (<i class="fas fa-book-reader"></i>): Llegar a la clase con los textos leídos.




| |<i class="fas fa-chalkboard-teacher"></i>  Clases  |  <i class="fas fa-user-edit"></i>  Prácticas y evaluaciones | <i class="fas fa-book-reader"></i> Lecturas y material adicional
-----|----|-----------|-----------
<font color="orange"> **Agosto** </font> |   |   |
Lunes 03 | [**00. Presentación**]() e [**01. Introducción y bases de regresión lineal**]()  |   | - Leer detalladamente [programa del curso](syllabus.html) <br> - Moore 1.1 y 1.2

### UNIDAD 1: El modelo de regresión lineal

|||
-----|----|-----------|-----------
Lunes 10 | [**02. Introducción al modelo de regresión OLS: repaso de funciones y definición general**]()  |   |
Lunes 17 | [**03. Regresión simple: estimador OLS y ecuación de la recta**]()  |   | - Wooldridge A1, A2 y 2.1 <br> - Moore 2.4.1
Lunes 24 | [**04. Regresión múltiple: parcialización y control estadístico**]()  |   | - Wooldridge 2.2 <br> - Moore 2.4.1
Lunes 31 | [**05. Regresión múltiple: interpretación y estandarización de coeficientes**]()  |   | - Wooldridge 3.1
<font color="orange"> **Septiembre** </font> |   |   |
Miércoles 02 |   | Ayudantía  |
Lunes 07 |   | **Prueba 1**  |
Lunes 14 | [**06. Inferencia estadística en regresión lineal**]()  |   | - Wooldridge 2.3 <br> - Moore 2.4.2
Lunes 21 | [**07. Valores predichos de regresión lineal**]()  |   | - Wooldridge 3.2-3.3
Miércoles 23 |   | Ayudantía  |
Lunes 28 | [**08. Variables dummy**]()  |   |
Miércoles 30 |   | Ayudantía  |
<font color="orange"> **Octubre** </font> |   |   |
Lunes 05 | [**09. Reporte y publicación: introducción a Quarto**]()  |   | - Wooldridge 3.2 y 6.3
Miércoles 07 |   | Ayudantía  |
Viernes 09 |   | **Trabajo 1**  |
Lunes 12 | Semana de consolidación de aprendizajes y autocuidado (sin actividades docentes)  |   |

### UNIDAD 2: Introducción a los modelos lineales generalizados (GLM)

|||
-----|----|-----------|-----------
Lunes 19 | [**10. Regresión logística I: Odds y Odds-ratio**]()  |   | - Camarero et al. (2017). *Regresión logística: fundamentos y aplicación a la investigación sociológica* (pp. 30-52)
Lunes 26 | [**11. Regresión logística II: coeficientes logit**]()  |   | - Cerda, Vera y Rada (2013). *Odds ratio: aspectos teóricos y prácticos*
<font color="orange"> **Noviembre** </font> |   |   |
Lunes 02 | [**12. Valores predichos de regresión logística**]()  |   | - Wooldridge cap. 7
Miércoles 04 |   | Ayudantía  |
Lunes 09 |   | **Prueba 2**  |
Miércoles 11 |   | Ayudantía  |

### UNIDAD 3: Supuestos del modelo de regresión lineal

|||
-----|----|-----------|-----------
Lunes 16 | [**13. Supuestos de regresión**]()  |   | - Wooldridge cap. 17
Lunes 23 | Sesión de asesoría de trabajo final  |   | - Wooldridge cap. 17
Miércoles 25 |   | Ayudantía  |
Viernes 27 |   | **Trabajo 2**  |
A definir |   | **Examen**  |
